version: '3'
services:
  mongodb:
    image: mongo:4.2.2-bionic
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./data:/data/dbo
  simple-web:
    image: nedwize/simple-web
    ports:
      - '80:3030'
      - '443:3030'
