version: '3'
services:
  mongodb:
    image: mongo:4.2.2-bionic
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  simple-web:
    image: nedwize/simple-web
    ports:
      - '80:3030'
      - '443:3030'
volumes:
  mongodata:
